// Generated by language/proto/gen/gen_known_imports.go
// From language/proto/proto.csv

package proto

import "github.com/bazelbuild/bazel-gazelle/label"

var knownGoProtoImports = map[string]label.Label{

	"github.com/golang/protobuf/ptypes/any":               label.New("io_bazel_rules_go", "proto/wkt", "any_go_proto"),
	"google.golang.org/genproto/protobuf/api":             label.New("io_bazel_rules_go", "proto/wkt", "api_go_proto"),
	"github.com/golang/protobuf/protoc-gen-go/plugin":     label.New("io_bazel_rules_go", "proto/wkt", "compiler_plugin_go_proto"),
	"github.com/golang/protobuf/protoc-gen-go/descriptor": label.New("io_bazel_rules_go", "proto/wkt", "descriptor_go_proto"),
	"github.com/golang/protobuf/ptypes/duration":          label.New("io_bazel_rules_go", "proto/wkt", "duration_go_proto"),
	"github.com/golang/protobuf/ptypes/empty":             label.New("io_bazel_rules_go", "proto/wkt", "empty_go_proto"),
	"google.golang.org/genproto/protobuf/field_mask":      label.New("io_bazel_rules_go", "proto/wkt", "field_mask_go_proto"),
	"google.golang.org/genproto/protobuf/source_context":  label.New("io_bazel_rules_go", "proto/wkt", "source_context_go_proto"),
	"github.com/golang/protobuf/ptypes/struct":            label.New("io_bazel_rules_go", "proto/wkt", "struct_go_proto"),
	"github.com/golang/protobuf/ptypes/timestamp":         label.New("io_bazel_rules_go", "proto/wkt", "timestamp_go_proto"),
	"google.golang.org/genproto/protobuf/ptype":           label.New("io_bazel_rules_go", "proto/wkt", "type_go_proto"),
	"github.com/golang/protobuf/ptypes/wrappers":          label.New("io_bazel_rules_go", "proto/wkt", "wrappers_go_proto"),
}
