// Generated by language/proto/gen/gen_known_imports.go
// From /opt/code/agentero/bazel-gazelle/language/proto/proto.csv

package proto

import "github.com/bazelbuild/bazel-gazelle/label"

var knownImports = map[string]label.Label{

	"google/protobuf/any.proto":             label.New("com_google_protobuf", "", "any_proto"),
	"google/protobuf/api.proto":             label.New("com_google_protobuf", "", "api_proto"),
	"google/protobuf/compiler/plugin.proto": label.New("com_google_protobuf", "", "compiler_plugin_proto"),
	"google/protobuf/descriptor.proto":      label.New("com_google_protobuf", "", "descriptor_proto"),
	"google/protobuf/duration.proto":        label.New("com_google_protobuf", "", "duration_proto"),
	"google/protobuf/empty.proto":           label.New("com_google_protobuf", "", "empty_proto"),
	"google/protobuf/field_mask.proto":      label.New("com_google_protobuf", "", "field_mask_proto"),
	"google/protobuf/source_context.proto":  label.New("com_google_protobuf", "", "source_context_proto"),
	"google/protobuf/struct.proto":          label.New("com_google_protobuf", "", "struct_proto"),
	"google/protobuf/timestamp.proto":       label.New("com_google_protobuf", "", "timestamp_proto"),
	"google/protobuf/type.proto":            label.New("com_google_protobuf", "", "type_proto"),
	"google/protobuf/wrappers.proto":        label.New("com_google_protobuf", "", "wrappers_proto"),
}
